# Use official Node.js image
FROM node:20-alpine

# Create app dir
WORKDIR /app

# Copy package files & install
COPY package*.json ./
RUN npm ci --only=production

# Copy source
COPY . .

# Expose port
EXPOSE 9092

# Run app
CMD [ "node", "index.js" ]
